[package]
name = "new-wordle-bot"
version = "0.1.0"
edition = "2024"

[dependencies]
base64 = "0.22.1"
bytemuck = "1.21.0"
fixedbitset = "0.5.7"
rayon = "1.10.0"
rustc-hash = "2.1.1"
smallvec = "1.14.0"
